apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.test.cattle.io
spec:
  group: test.cattle.io
  scope: Namespaced
  names:
    plural: foos 
    singular: foo
    kind: Foo 
  versions:
    - name: v1
      served: true
      # Need to have exactly one storage version
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "desired spec of the resource"
              properties:
                initialField:
                  type: string
                  description: "a field that has the same meaning through each version"
                removedField:
                  type: string
                  description: "a field that will be removed in a future version"
    - name: v2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "desired spec of the resource"
              properties:
                initialField:
                  type: string
                  description: "a field that has the same meaning through each version"
                addedField:
                  type: string
                  description: "a field that is added in a future version"
